config/routes.rb
Rails.application.routes.draw do
  # get 'product/index'
  # get '/product/new' , to: "product#new"
  # get '/product/:id' , to: "product#show"
  # get '/product/:id' , to: "product#edit"
  # patch '/product/:id' , to: "product#update"
  # delete '/product/:id' , to: "product#destroy"
  # root "product#index"
  resources :product do
    resources :admins
  end
end

=begin 
   Controller#Action
                                    root GET    /                                                                                                 product#index
                           product_index GET    /product(.:format)                                                                                product#index
                                         POST   /product(.:format)                                                                                product#create
                             new_product GET    /product/new(.:format)                                                                            product#new
                            edit_product GET    /product/:id/edit(.:format)                                                                       product#edit
                                 product GET    /product/:id(.:format)                                                                            product#show
                                         PATCH  /product/:id(.:format)                                                                            product#update
                                         PUT    /product/:id(.:format)                                                                            product#update
                                         DELETE /product/:id(.:format) 
=end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :admin
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_controller.rb
class ProductController < ApplicationController


  http_basic_authenticate_with name: "adham", password: "secret", except: [:index, :show]
  # , only: [:destory]

  def index
   @products = Product.all()
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def product_params
    params.require(:product).permit(:name, :description , :price , :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product/_form.html.erb
<%= form_with model: product do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
     <% product.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
      <% product.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
          <% product.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <div>
    <%= form.label :image %><br>
    <%= form.text_field :image %>
          <% product.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.label :Admin %><br>
    <%= form.text_field :admin %>
          <% @product.errors.full_messages_for(:Admin).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product/edit.html.erb
<h1>Edit Article</h1>
<%=  render 'form' , product: @product %>

app/views/product/index.html.erb
<h1>Products List</h1>

<a href="/product/new">create product</a>

<% @products.each do |products| %>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><%= products.name %></td>
                <td><%= products.description %></td>
                <td><%= products.price %></td>
                <td>
                 <a href="/product/<%= products.id %>">Show</a>
                 <a href="/product/<%= products.id %>/edit">Edit</a>
                </td>
            </tr>
        </tbody>
    </table>
    
<% end %>

app/views/product/new.html.erb
<h1>New Article</h1>
<%=  render 'form' , product: @product %>

  <% 
=begin %> 

      <div>
    <%= form.label :Admin %><br>
    <%= form.text_field :admin %>
          <% @product.errors.full_messages_for(:Admin).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  
<% 
=end %>

app/views/product/show.html.erb
<h2><%= @product.name %> <h1>
<h4><%= @product.description %> <h4>
<h3><%= @product.price %> <h3>
<img src = "<%= @product.image %>" alt = "img"/>

<ul>
  <li><%= link_to "Edit", edit_product_path(@product) %></li>
  <li>
  <%= link_to "Destroy", product_path(@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  </li>
</ul>